import 'package:flutter/material.dart';

/// Enum representing the possible states of a desk.
enum DeskStatus {
  available,
  occupied,
  reserved,
  selected,
  maintenance;

  /// Material 3 fill color
  Color get color {
    switch (this) {
      case DeskStatus.available:
        return const Color(0xFF81C784); // Soft Green
      case DeskStatus.occupied:
        return const Color(0xFFE53935); // Red (Ocupada)
      case DeskStatus.reserved:
        return const Color(0xFFFFB74D); // Amber / Colega Depto
      case DeskStatus.selected:
        return const Color(0xFF1E88E5); // Vibrant Blue
      case DeskStatus.maintenance:
        return const Color(0xFFF59E0B); // Amber / Manutenção Facilities
    }
  }

  /// Soft container color for badges and cards
  Color get containerColor {
    switch (this) {
      case DeskStatus.available:
        return const Color(0xFFE8F5E9);
      case DeskStatus.occupied:
        return const Color(0xFFFEF2F2);
      case DeskStatus.reserved:
        return const Color(0xFFFFFBEB);
      case DeskStatus.selected:
        return const Color(0xFFE3F2FD);
      case DeskStatus.maintenance:
        return const Color(0xFFFEF3C7);
    }
  }

  /// High-contrast text color on top of containerColor
  Color get onContainerColor {
    switch (this) {
      case DeskStatus.available:
        return const Color(0xFF2E7D32);
      case DeskStatus.occupied:
        return const Color(0xFFB91C1C);
      case DeskStatus.reserved:
        return const Color(0xFFB45309);
      case DeskStatus.selected:
        return const Color(0xFF1565C0);
      case DeskStatus.maintenance:
        return const Color(0xFF92400E);
    }
  }

  /// Human-readable label in Portuguese
  String get label {
    switch (this) {
      case DeskStatus.available:
        return 'Disponível';
      case DeskStatus.occupied:
        return 'Ocupada';
      case DeskStatus.reserved:
        return 'Colega Depto';
      case DeskStatus.selected:
        return 'Sua Reserva';
      case DeskStatus.maintenance:
        return 'Em Manutenção';
    }
  }

  /// Associated icon for UI indicators
  IconData get icon {
    switch (this) {
      case DeskStatus.available:
        return Icons.check_circle_outline_rounded;
      case DeskStatus.occupied:
        return Icons.lock_outline_rounded;
      case DeskStatus.reserved:
        return Icons.access_time_rounded;
      case DeskStatus.selected:
        return Icons.radio_button_checked_rounded;
      case DeskStatus.maintenance:
        return Icons.build_rounded;
    }
  }
}

/// Immutable model representing a single hot-desk station extracted from the SVG floorplan.
@immutable
class DeskModel {
  final String id;
  final String number;
  final double dx;
  final double dy;
  final double width;
  final double height;
  final double rotationDegrees;
  final DeskStatus status;
  final String zone;
  final String? occupantName;
  final String? occupantDepartment;
  final List<String> amenities;

  const DeskModel({
    required this.id,
    required this.number,
    required this.dx,
    required this.dy,
    required this.width,
    required this.height,
    this.rotationDegrees = 0.0,
    this.status = DeskStatus.available,
    this.zone = 'Geral',
    this.occupantName,
    this.occupantDepartment,
    this.amenities = const [],
  });

  bool get isAvailable => status == DeskStatus.available;
  bool get isOccupied => status == DeskStatus.occupied;
  bool get isReserved => status == DeskStatus.reserved;
  bool get isSelected => status == DeskStatus.selected;
  bool get isMaintenance => status == DeskStatus.maintenance;


  DeskModel copyWith({
    String? id,
    String? number,
    double? dx,
    double? dy,
    double? width,
    double? height,
    double? rotationDegrees,
    DeskStatus? status,
    String? zone,
    String? occupantName,
    String? occupantDepartment,
    List<String>? amenities,
  }) {
    return DeskModel(
      id: id ?? this.id,
      number: number ?? this.number,
      dx: dx ?? this.dx,
      dy: dy ?? this.dy,
      width: width ?? this.width,
      height: height ?? this.height,
      rotationDegrees: rotationDegrees ?? this.rotationDegrees,
      status: status ?? this.status,
      zone: zone ?? this.zone,
      occupantName: occupantName ?? this.occupantName,
      occupantDepartment: occupantDepartment ?? this.occupantDepartment,
      amenities: amenities ?? this.amenities,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeskModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          status == other.status;

  @override
  int get hashCode => id.hashCode ^ status.hashCode;
}

/// Exact desk coordinates for the Berrini floor plan (102 desks).
/// All default to DeskStatus.available with no mock presets.
const List<DeskModel> berriniSvgDesks = [
    DeskModel(
      id: 'berrini_desk_01',
      number: '01',
      dx: 12.0,
      dy: 333.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_02',
      number: '02',
      dx: 55.0,
      dy: 332.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_03',
      number: '03',
      dx: 98.0,
      dy: 332.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_04',
      number: '04',
      dx: 141.0,
      dy: 332.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_05',
      number: '05',
      dx: 141.0,
      dy: 309.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_06',
      number: '06',
      dx: 98.0,
      dy: 309.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_07',
      number: '07',
      dx: 55.0,
      dy: 309.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_08',
      number: '08',
      dx: 12.0,
      dy: 309.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_09',
      number: '09',
      dx: 12.0,
      dy: 237.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_10',
      number: '10',
      dx: 55.0,
      dy: 237.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_11',
      number: '11',
      dx: 98.0,
      dy: 237.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_12',
      number: '12',
      dx: 141.0,
      dy: 237.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_13',
      number: '13',
      dx: 141.0,
      dy: 214.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_14',
      number: '14',
      dx: 98.0,
      dy: 214.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_15',
      number: '15',
      dx: 55.0,
      dy: 214.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_16',
      number: '16',
      dx: 12.0,
      dy: 214.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_17',
      number: '17',
      dx: 308.0,
      dy: 300.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_18',
      number: '18',
      dx: 308.0,
      dy: 261.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_19',
      number: '19',
      dx: 308.0,
      dy: 222.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_20',
      number: '20',
      dx: 334.0,
      dy: 300.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_21',
      number: '21',
      dx: 334.0,
      dy: 261.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_22',
      number: '22',
      dx: 334.0,
      dy: 222.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_23',
      number: '23',
      dx: 417.0,
      dy: 300.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_24',
      number: '24',
      dx: 417.0,
      dy: 261.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_25',
      number: '25',
      dx: 417.0,
      dy: 222.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_26',
      number: '26',
      dx: 443.0,
      dy: 300.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_27',
      number: '27',
      dx: 443.0,
      dy: 261.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_28',
      number: '28',
      dx: 443.0,
      dy: 222.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_29',
      number: '29',
      dx: 526.0,
      dy: 300.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_30',
      number: '30',
      dx: 526.0,
      dy: 261.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_31',
      number: '31',
      dx: 526.0,
      dy: 222.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_32',
      number: '32',
      dx: 552.0,
      dy: 300.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_33',
      number: '33',
      dx: 552.0,
      dy: 261.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_34',
      number: '34',
      dx: 552.0,
      dy: 222.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_35',
      number: '35',
      dx: 635.0,
      dy: 300.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_36',
      number: '36',
      dx: 635.0,
      dy: 261.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_37',
      number: '37',
      dx: 635.0,
      dy: 222.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_38',
      number: '38',
      dx: 661.0,
      dy: 300.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_39',
      number: '39',
      dx: 661.0,
      dy: 261.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_40',
      number: '40',
      dx: 661.0,
      dy: 222.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_41',
      number: '41',
      dx: 744.0,
      dy: 300.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_42',
      number: '42',
      dx: 744.0,
      dy: 261.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_43',
      number: '43',
      dx: 744.0,
      dy: 222.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_44',
      number: '44',
      dx: 770.0,
      dy: 300.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_45',
      number: '45',
      dx: 770.0,
      dy: 261.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_46',
      number: '46',
      dx: 770.0,
      dy: 222.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_47',
      number: '47',
      dx: 853.0,
      dy: 300.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_48',
      number: '48',
      dx: 853.0,
      dy: 261.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_49',
      number: '49',
      dx: 853.0,
      dy: 222.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_50',
      number: '50',
      dx: 879.0,
      dy: 300.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_51',
      number: '51',
      dx: 879.0,
      dy: 261.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_52',
      number: '52',
      dx: 879.0,
      dy: 222.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_53',
      number: '53',
      dx: 470.0,
      dy: 142.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_54',
      number: '54',
      dx: 470.0,
      dy: 103.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_55',
      number: '55',
      dx: 470.0,
      dy: 64.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_56',
      number: '56',
      dx: 470.0,
      dy: 25.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_57',
      number: '57',
      dx: 496.0,
      dy: 142.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_58',
      number: '58',
      dx: 496.0,
      dy: 103.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_59',
      number: '59',
      dx: 496.0,
      dy: 64.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_60',
      number: '60',
      dx: 496.0,
      dy: 25.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_61',
      number: '61',
      dx: 579.0,
      dy: 142.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_62',
      number: '62',
      dx: 579.0,
      dy: 103.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_63',
      number: '63',
      dx: 579.0,
      dy: 64.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_64',
      number: '64',
      dx: 579.0,
      dy: 25.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_65',
      number: '65',
      dx: 605.0,
      dy: 142.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_66',
      number: '66',
      dx: 605.0,
      dy: 103.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_67',
      number: '67',
      dx: 605.0,
      dy: 64.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_68',
      number: '68',
      dx: 605.0,
      dy: 25.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_69',
      number: '69',
      dx: 688.0,
      dy: 142.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_70',
      number: '70',
      dx: 688.0,
      dy: 103.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_71',
      number: '71',
      dx: 688.0,
      dy: 64.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_72',
      number: '72',
      dx: 688.0,
      dy: 25.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_73',
      number: '73',
      dx: 714.0,
      dy: 142.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_74',
      number: '74',
      dx: 714.0,
      dy: 103.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_75',
      number: '75',
      dx: 714.0,
      dy: 64.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_76',
      number: '76',
      dx: 714.0,
      dy: 25.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_77',
      number: '77',
      dx: 797.0,
      dy: 142.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_78',
      number: '78',
      dx: 797.0,
      dy: 103.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_79',
      number: '79',
      dx: 797.0,
      dy: 64.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_80',
      number: '80',
      dx: 797.0,
      dy: 25.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_81',
      number: '81',
      dx: 823.0,
      dy: 142.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_82',
      number: '82',
      dx: 823.0,
      dy: 103.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_83',
      number: '83',
      dx: 823.0,
      dy: 64.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_84',
      number: '84',
      dx: 823.0,
      dy: 25.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_85',
      number: '85',
      dx: 576.0,
      dy: 458.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_86',
      number: '86',
      dx: 576.0,
      dy: 419.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_87',
      number: '87',
      dx: 576.0,
      dy: 380.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_88',
      number: '88',
      dx: 602.0,
      dy: 458.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_89',
      number: '89',
      dx: 602.0,
      dy: 419.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_90',
      number: '90',
      dx: 602.0,
      dy: 380.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_91',
      number: '91',
      dx: 685.0,
      dy: 458.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_92',
      number: '92',
      dx: 685.0,
      dy: 419.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_93',
      number: '93',
      dx: 685.0,
      dy: 380.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_94',
      number: '94',
      dx: 711.0,
      dy: 458.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_95',
      number: '95',
      dx: 711.0,
      dy: 419.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_96',
      number: '96',
      dx: 711.0,
      dy: 380.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_97',
      number: '97',
      dx: 794.0,
      dy: 458.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_98',
      number: '98',
      dx: 794.0,
      dy: 419.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_99',
      number: '99',
      dx: 794.0,
      dy: 380.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_100',
      number: '100',
      dx: 820.0,
      dy: 458.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_101',
      number: '101',
      dx: 820.0,
      dy: 419.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'berrini_desk_102',
      number: '102',
      dx: 820.0,
      dy: 380.0,
      width: 21.0,
      height: 34.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
];

const List<DeskModel> barueriDesks = [
    DeskModel(
      id: 'barueri_desk_01',
      number: '01',
      dx: 117.5,
      dy: 590.5,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 90.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_02',
      number: '02',
      dx: 117.5,
      dy: 547.5,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 90.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_03',
      number: '03',
      dx: 140.5,
      dy: 590.5,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 90.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_04',
      number: '04',
      dx: 140.5,
      dy: 547.5,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 90.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_05',
      number: '05',
      dx: 261.5,
      dy: 603.5,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 90.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_06',
      number: '06',
      dx: 261.5,
      dy: 560.5,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 90.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_07',
      number: '07',
      dx: 238.2,
      dy: 514.7,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_08',
      number: '08',
      dx: 204.2,
      dy: 481.7,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_09',
      number: '09',
      dx: 284.5,
      dy: 603.5,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 90.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_10',
      number: '10',
      dx: 284.5,
      dy: 560.5,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 90.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_11',
      number: '11',
      dx: 255.2,
      dy: 497.7,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_12',
      number: '12',
      dx: 222.2,
      dy: 464.7,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_13',
      number: '13',
      dx: 387.6,
      dy: 510.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_14',
      number: '14',
      dx: 355.8,
      dy: 478.2,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_15',
      number: '15',
      dx: 324.0,
      dy: 446.4,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_16',
      number: '16',
      dx: 292.1,
      dy: 414.6,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_17',
      number: '17',
      dx: 403.9,
      dy: 493.8,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_18',
      number: '18',
      dx: 372.0,
      dy: 461.9,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_19',
      number: '19',
      dx: 339.5,
      dy: 430.8,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_20',
      number: '20',
      dx: 307.7,
      dy: 399.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_21',
      number: '21',
      dx: 480.2,
      dy: 438.6,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_22',
      number: '22',
      dx: 448.4,
      dy: 406.8,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_23',
      number: '23',
      dx: 416.6,
      dy: 375.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_24',
      number: '24',
      dx: 496.5,
      dy: 422.3,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_25',
      number: '25',
      dx: 464.7,
      dy: 390.5,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_26',
      number: '26',
      dx: 432.1,
      dy: 359.4,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_27',
      number: '27',
      dx: 575.0,
      dy: 329.7,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_28',
      number: '28',
      dx: 543.2,
      dy: 297.9,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_29',
      number: '29',
      dx: 480.0,
      dy: 284.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_30',
      number: '30',
      dx: 430.0,
      dy: 284.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_31',
      number: '31',
      dx: 379.0,
      dy: 284.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_32',
      number: '32',
      dx: 591.2,
      dy: 313.5,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_33',
      number: '33',
      dx: 559.4,
      dy: 281.6,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_34',
      number: '34',
      dx: 479.0,
      dy: 259.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_35',
      number: '35',
      dx: 429.0,
      dy: 259.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_36',
      number: '36',
      dx: 379.0,
      dy: 259.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_37',
      number: '37',
      dx: 658.4,
      dy: 260.4,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_38',
      number: '38',
      dx: 626.6,
      dy: 228.6,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_39',
      number: '39',
      dx: 594.8,
      dy: 196.8,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_40',
      number: '40',
      dx: 532.0,
      dy: 186.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_41',
      number: '41',
      dx: 481.0,
      dy: 186.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_42',
      number: '42',
      dx: 430.0,
      dy: 186.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_43',
      number: '43',
      dx: 379.0,
      dy: 186.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_44',
      number: '44',
      dx: 674.7,
      dy: 244.2,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_45',
      number: '45',
      dx: 642.9,
      dy: 212.3,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_46',
      number: '46',
      dx: 610.3,
      dy: 181.2,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_47',
      number: '47',
      dx: 531.0,
      dy: 161.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_48',
      number: '48',
      dx: 480.0,
      dy: 161.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_49',
      number: '49',
      dx: 429.0,
      dy: 161.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_50',
      number: '50',
      dx: 379.0,
      dy: 161.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_51',
      number: '51',
      dx: 710.7,
      dy: 160.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_52',
      number: '52',
      dx: 678.9,
      dy: 128.2,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_53',
      number: '53',
      dx: 647.1,
      dy: 96.4,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_54',
      number: '54',
      dx: 583.0,
      dy: 83.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_55',
      number: '55',
      dx: 532.0,
      dy: 83.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_56',
      number: '56',
      dx: 481.0,
      dy: 83.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_57',
      number: '57',
      dx: 430.0,
      dy: 83.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_58',
      number: '58',
      dx: 379.0,
      dy: 83.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_59',
      number: '59',
      dx: 727.0,
      dy: 143.7,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_60',
      number: '60',
      dx: 695.2,
      dy: 111.9,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_61',
      number: '61',
      dx: 662.7,
      dy: 80.8,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 45.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_62',
      number: '62',
      dx: 582.0,
      dy: 58.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_63',
      number: '63',
      dx: 531.0,
      dy: 58.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_64',
      number: '64',
      dx: 480.0,
      dy: 58.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_65',
      number: '65',
      dx: 429.0,
      dy: 58.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
    DeskModel(
      id: 'barueri_desk_66',
      number: '66',
      dx: 379.0,
      dy: 58.0,
      width: 38.0,
      height: 19.0,
      rotationDegrees: 0.0,
      status: DeskStatus.available,
    ),
];

const List<DeskModel> berriniDesks = berriniSvgDesks;

/// Retorna a lista canônica de mesas de acordo com o escritório
List<DeskModel> getDesksForOffice(String? officeName) {
  if (officeName != null && officeName.toLowerCase().contains('barueri')) {
    return barueriDesks;
  }
  return berriniSvgDesks;
}
